admin_facing/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "admin_facing"

urlpatterns = [
    path("home/", views.user_home_view, name="home"),
    path("category/", views.app_view, name="app"),
    path("task_create/<int:app_id>/", views.task_create, name="task_create"),
    path("task_claimed/", views.task_claimed, name="task_claimed"),
    path("task_claimed_list/", views.user_claimed_task_list, name="task_claimed_list")
    # path("appdownloaded/", views.userdownloadapp, name="appdownloaded"),
]

reward/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user_facing.urls")),
    path("user_facing/", include("django.contrib.auth.urls")),
    path("admin_facing/", include("admin_facing.urls")),
]

user_facing/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app = "user_facing"

urlpatterns = [
    # path("", views.index, name="home"),
    path("user_facing/login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("profile/", views.profile_view, name="profile")
    # path("userfacing/profile/", views.profile_view, name="profile_view"),
]

admin_facing/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Application(models.Model):
    Socialmedia = "Socialmedia"
    Heatlhmanagement = "HealthManagement"
    Entertainment = "Entertainment"
    Educational = "Educational"
    Productivity = "Productivity"
    Lifestyle = "Lifestyle"
    FIELD_IN_CATEGORY_CHOICES = [
        (Socialmedia, "Socialmedia"),
        (Heatlhmanagement, "Heatlhmanagement"),
        (Entertainment, "Entertainment"),
        (Educational, " Educational"),
        (Productivity, "Productivity"),
        (Lifestyle, "Lifestyle"),
    ]
    category = models.CharField(
        max_length=200,
        choices=FIELD_IN_CATEGORY_CHOICES,
        default=Socialmedia,
    )

    name = models.CharField(max_length=200)
    points = models.IntegerField()


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    image = models.ImageField()

user_facing/models.py
from django.db import models
from django.conf import settings

admin_facing/forms.py
from django import forms

from .models import Application, Task


class AppForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = (
            "category",
            "name",
            "points",
        )


class AppList(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["image"]


"""class AppDownloaded(forms.ModelForm):
    class Meta:
        model = App_list
        fields = (
            "Appname",
            "Points",
            "app_download",
        )
"""

user_facing/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)

User = get_user_model()


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label="Email Address")
    email2 = forms.EmailField(label="Confirm Email")
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "email", "email2", "password"]

    def clean_email2(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")
        if email != email2:
            raise forms.ValidationError("Email must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return email


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("this user does not exit")
            if not user.check_password(password):
                raise forms.ValidationError("incorrect password")
            if not user.is_active:
                raise forms.ValidationError("this user is not longer active")
        return super(UserLoginForm, self).clean(*args, **kwargs)

admin_facing/views.py
from django.shortcuts import render, redirect, reverse
from .models import Application, Task
from .forms import AppForm, AppList
from django.core.files.storage import FileSystemStorage
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


@staff_member_required
def app_view(request):
    if request.method == "POST":
        form = AppForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = AppForm()
    context = {"form": form}
    return render(request, "admin_facing/app.html", context)


@login_required
def task_create(request, app_id):
    app = Application.objects.get(id=app_id)
    if request.method == "POST":
        # app_id = request.kwargs.get("app_id")
        form = AppList(request.POST, request.FILES)
        if form.is_valid():
            img = form.cleaned_data["image"]
            fs = FileSystemStorage()
            image = fs.save(img.name, img)
            qs = Task.objects.filter(user=request.user, application=app)
            if qs.exists():
                messages.warning(request, "user already exists.")
                return redirect(reverse("admin_facing:home"))
            task = Task.objects.create(user=request.user, application=app, image=image)
            return redirect(reverse("admin_facing:task_claimed"))
    else:
        form = AppList()
    context = {"form": form, "app": app}
    return render(request, "admin_facing/app_list.html", context)


def user_home_view(request):
    app = Application.objects.all()
    context = {"app": app}
    return render(request, "admin_facing/task_create.html", context)


@login_required
def task_claimed(request):
    user = request.user
    tasks = Task.objects.filter(user=user)
    points = 0
    for task in tasks:
        points += task.application.points
    context = {"points": points, "tasks": tasks}
    return render(request, "admin_facing/task_claimed.html", context)


@login_required
def user_claimed_task_list(request):
    user = request.user
    tasks = Task.objects.filter(user=user)
    context = {"tasks": tasks}
    return render(request, "admin_facing/task_claimed_list.html", context)

user_facing/views.py
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegisterForm
from django.urls import reverse
from django.template.context_processors import csrf

User = get_user_model()


def login_view(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect(reverse("admin_facing:home"))
    return render(request, "user_facing/form.html", {"form": form})


def register_view(request):
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get("password")
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        return redirect("/")

    context = {"form": form}
    return render(request, "user_facing/form.html", context)


def logout_view(request):
    logout(request)
    return redirect(reverse("user_facing:login"))


def profile_view(request):
    users = User.objects.all()
    context = {"users": users}
    return render(request, "user_facing/user_profile.html", context)

admin_facing/templates/admin_facing/app.html
{% block content %}
<form method="Post" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='save' />
</form>
{% endblock %}

admin_facing/templates/admin_facing/app_downloaded.html
{% for app in downloaded_app %}
{% csrf_token %}
appname:{{ app.Appname }}<br>
points:{{ app.Points }}<br>
downloadedapp:{{ app.app_download }}<br>
{% endfor %}

admin_facing/templates/admin_facing/app_list.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
appname:{{ app.name }}<br>
points:{{ app.points }}<br>
<form method="POST" action="{% url 'admin_facing:task_create' app.id %}" enctype="multipart/form-data"
    class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"> <br>
</form>

admin_facing/templates/admin_facing/task_claimed.html
{% csrf_token %}
user:{{ user }}<br>
points:{{ points }}<br>

admin_facing/templates/admin_facing/task_claimed_list.html
{% for task in tasks %}
username:{{ task.user }}<br>
appnamae:{{task.application.name}}<br>
points:{{ task.application.points }}<br>
{% endfor %}

admin_facing/templates/admin_facing/task_create.html
<a href="{% url 'login' %}">login</a><br>
<a href="{% url 'logout' %}">logout</a><br>
<a href="{% url 'profile' %}">userprofile</a><br>
<a href="{% url 'admin_facing:task_claimed' %}">userpoints</a><br>

{% for application in app %}
{% csrf_token %}
appname:{{ application.name }}<br>
points:{{ application.points }}<br>
<a href="{% url 'admin_facing:task_create' application.id %}">{{ application.name }}</a><br>
{% endfor %}

user_facing/templates/user_facing/form.html
{% block content %}
<form method="Post" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='save' />
</form>
Don't have an register? <a href="{% url 'register' %}" target="blank">register</a>
{% endblock %}

user_facing/templates/user_facing/index.html
<h1> {{user}} </h1>

user_facing/templates/user_facing/user_profile.html
{% for user in users %}
username:{{ user.username }}<br>
email:{{user.email}}<br>
{% endfor %}